#!/usr/bin/env ruby
require 'sinatra'
require 'tempfile'
require 'fileutils'

include FileUtils

get '/' do 
  ip = request.ip
  "you ip is #{ip}"
end

get '/save/as/:name' do |name|
  save_ip( request.ip, name )
  "saved, your ip is #{request.ip}"
end

def save_ip( ip, name )
  tmp = Tempfile.new('hosts')
  begin
    File.foreach( hosts_file ) do |line|
      unless line =~ %r(#{ip}\s+#{name})
        tmp << line
      end
    end

    tmp << "\n#{ip} #{name} #auto generated by Rember-My-IP\n"
    tmp.close

    cp tmp, hosts_file

  ensure
    tmp.unlink
  end

end

def hosts_file
  RUBY_PLATFORM =~ /w(in)?32/ ? 
    'C:/WINDOWS/system32/drivers/etc/hosts' : 
    '/etc/hosts'
end

if ARGV.include? "disable-run"
  disable :run
end
